doctrine_migrations:
    migrations_paths:
        'App\Shared\Infrastructure\Doctrine\Migration': '%kernel.project_dir%/src/Shared/Infrastructure/Doctrine/Migrations'
    enable_profiler: '%kernel.debug%'
