doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Shared\Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Shared\Domain'
            App\Product\Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Product/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Product\Domain'